name: Build AbstractServer

on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - 'README.md'
      - './src/index.ts'
      - './coverage/**/*'
  pull_request:
    branches: [ 'main' ]
    paths-ignore:
      - 'README.md'
      - './src/index.ts'
      - './coverage/**/*'
  release:
    types:
      - 'created'

env:
  GIT_MAIL: 'monstermichl@users.noreply.github.com'
  GIT_USER: 'monstermichl'

jobs:
  generate_index_ts:
    name: Generate index.ts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate index.ts
        shell: bash
        run: ./.github/scripts/generate-index-ts.sh
      - name: Push index.ts
        if: ${{ github.event_name != 'release' }}
        run: |
          git pull
          git config --global user.email "$GIT_MAIL"
          git config --global user.name "$GIT_USER"
          git commit ./src/index.ts -m 'Generate index.ts'
          git push

  lint:
    name: Lint source
    runs-on: ubuntu-latest
    needs: generate_index_ts
    steps:
      - uses: actions/checkout@v3
      - name: Lint source
        run: |
          npm ci
          npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Run Unittest
        run: |
          npm ci
          npm run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build

  update_readme:
    name: Update README.md
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name != 'release' }}
    steps:
    - uses: actions/checkout@v3
    - name: Run README.md generator
      shell: bash
      run: ./.github/scripts/build-readme.sh
    - name: Push README.md
      shell: bash
      run: |
        README_FILE="README.md"
        README_BEFORE_PULL=$(cat "${README_FILE}")
        git pull
        README_AFTER_PULL=$(cat "${README_FILE}")

        echo "-----------------------------------------------"
        echo "README before pull:"
        echo "${README_BEFORE_PULL}"
        echo "-----------------------------------------------"
        echo "README after pull:"
        echo "${README_AFTER_PULL}"
        echo "-----------------------------------------------"

        if [[ "${README_BEFORE_PULL}" != "${README_AFTER_PULL}" ]]; then
          git config --global user.email "$GIT_MAIL"
          git config --global user.name "$GIT_USER"
          git commit README.md -m "Generate README.md"
          git push
        else
          echo "README didn't change"
        fi

  # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'release' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      #- run: npx npm-packlist
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
