name: Build AbstractServer

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - "./src/index.ts"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - "./src/index.ts"

jobs:
  generate_index_ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate index.ts
        shell: bash
        run: ./.github/scripts/generate-index-ts.sh
      - name: Push index.ts
        run: |
          git pull
          git config --global user.email "monstermichl@users.noreply.github.com"
          git config --global user.name "monstermichl"
          git commit ./src/index.ts -m "Generate index.ts"
          git push

  lint:
    runs-on: ubuntu-latest
    needs: generate_index_ts
    steps:
      - uses: actions/checkout@v3
      - name: Lint source
        run: |
          npm ci
          npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
